language: node_js

node_js:
  - "4.2.6"

branches:
 only:
   - master

before_install:
  - npm install -g bower grunt npm@3.5.2

install:
  - npm -v
  - node -v
  - npm install
  - bower install
  - ls -la node_modules/

script:
  - grunt travis -v